### ISSUE TITLE
Quaver crashes when 2 users from 2 different servers consecutively leave and rejoin a channel.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#55] opened 2021-12-30 17:00 UTC
**Describe the bug**
The possibility of this bug happening is very low on normal usage.
Can happen with either Voice or Stage channels. 

Quaver crashes on a certain instance where 2 users from 2 different servers consecutively leave and rejoin a channel then 1 user disconnects Quaver on the other server. 

**To Reproduce**
Legend:
user1 is from server1
user2 is from server2
Quaver on both servers have administrator permissions.
Time interval of them leaving a channel does not matter.

1. user1 joins a voice channel on server1
2. user1 uses the play command as usual then leaves after
3. user2 joins a voice channel on server2
4. user2 uses the play command as usual then leaves after
5. user1 joins back to the voice channel on server1
6. Quaver on server1 resumes its session
7. user1 left the voice channel
8. user2 joins back to the voice channel on server2
9. Quaver on server2 resumes its session
10. user2 uses /disconnect on Quaver since user2 no longer wants to play.
11. Quaver crashes and shows that it crashed on server1
12. See error on `error.log`
```
unhandledRejection
Cannot read properties of undefined (reading 'queue')
TypeError: Cannot read properties of undefined (reading 'queue')
    at Client.<anonymous> (C:\Users\A\Desktop\Quaver-3.0.0-next.2\main.js:451:27)
    at Client.emit (node:events:390:28)
    at VoiceStateUpdate.handle (C:\Users\A\Desktop\Quaver-3.0.0-next.2\node_modules\discord.js\src\client\actions\VoiceStateUpdate.js:38:14)
    at Object.module.exports [as VOICE_STATE_UPDATE] (C:\Users\A\Desktop\Quaver-3.0.0-next.2\node_modules\discord.js\src\client\websocket\handlers\VOICE_STATE_UPDATE.js:4:35)
    at WebSocketManager.handlePacket (C:\Users\A\Desktop\Quaver-3.0.0-next.2\node_modules\discord.js\src\client\websocket\WebSocketManager.js:350:31)
    at WebSocketShard.onPacket (C:\Users\A\Desktop\Quaver-3.0.0-next.2\node_modules\discord.js\src\client\websocket\WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (C:\Users\A\Desktop\Quaver-3.0.0-next.2\node_modules\discord.js\src\client\websocket\WebSocketShard.js:300:10)
    at WebSocket.onMessage (C:\Users\A\Desktop\Quaver-3.0.0-next.2\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (C:\Users\A\Desktop\Quaver-3.0.0-next.2\node_modules\ws\lib\websocket.js:1022:20)
```

**Expected behavior**
Quaver should still be operating as normal even if a user left & rejoin channels or disconnected Quaver on such vague situations.

**Comment by zapteryx** [comment] 2021-12-31 03:24
i've pushed a fix for this, but i have no idea what implications the fix may have, so please look out for any other bugs that may be caused by this fix

**Closed** 2022-01-02 18:11 UTC
Labels: bug, released on @next
