### ISSUE TITLE
Quaver crashes when it consecutively sets pause time out for 2 users on 2 different servers.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#58] opened 2021-12-31 20:12 UTC
**Describe the bug**
Quaver crashes once it consecutively leaves 2 different kind of channels from 2 different servers from the pause time out feature.

This is not reprodocible when both Quavers are in voice channels.
One quaver should be in a stage channel.
The other quaver on the other server should be in a voice channel.

**To Reproduce**
Legend:
user1 on server1
user2 on server2
They both have to leave the channel consecutively.

# Trimmed version of the steps
> Just the important steps to reproduce the behavior.

1. user1: Joins stage channel and play with Quaver on server1
2. user2: Joins voice channel and play with Quaver on server2
3. Make the users leave in this order.
- user1 leaves the channel first.
- user2 leaves the channel last.
4. user1: Joins the stage channel again and leaves right after 
5. Simply wait for pause timeout, then after 5 minutes, Quaver shall leave in this order and crash.
- user2's pause time out shall be commenced first
> = Quaver on server2 will leave from inactivity first.
- user1's pause time out shall be commenced last since user1 joined back and resumed its session and left on Step 4.
> = Quaver on server1 will leave from inactivity last.
6. See error.
```
unhandledRejection
Unknown Voice State
DiscordAPIError: Unknown Voice State
    at RequestHandler.execute (/home/runner/GullibleQuestionableActivemovie/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/runner/GullibleQuestionableActivemovie/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async VoiceState.setSuppressed (/home/runner/GullibleQuestionableActivemovie/node_modules/discord.js/src/structures/VoiceState.js:254:5)
```

# Detailed version of the steps
> It's just more detailed on what's going to happen.

Alternative for Steps 1 and 2:
> If choosing the alternative, after doing these 2 steps, do step 5 directly. And wait for 5 minutes and it shall crash the same way it did wit the original steps.

1. user1 plays a music using Quaver in server1 (STAGE CHANNEL) then leaves right after.
2. user2 plays a music using Quaver in server2 (VOICE CHANNEL) then leaves right after.

**Original steps**:
1. user1 plays a music using Quaver in server1 (STAGE CHANNEL)
2. user2 plays a music using Quaver in server2 (VOICE CHANNEL)
3. Both users consecutively leaves the channels where Quaver is playing:
Both must leave the channel in this order.
Current order:
- user1 left the stage channel (1st) - Quaver (server1) will leave first 
- user2 left the voice channel (2nd) - Quaver (server2) will leave after Quaver on server1 leaves.
4. Quaver sets pause time out for both of these users consecutively for this.
5. user1 comes back to the channel where Quaver is playing then leaves right after.
For this reason, Quaver sets pause time out on user1 again.
6. Wait for pause time out, the trigger of the crash would be Quaver on server2
since:
- user2 was the last user Quaver set a pause time out on so user2's timeout will now be first instead of user1
because:
- user1 came back to channel on step 5
> Quaver sets pause time out on user1 again so pause time out was reset for user1 therefore Quaver on server2 will leave the channel first before Quaver on server1
so the order is now this

**Before**:
- user1 left the stage channel (1st) - Quaver (server1) will leave first 
- user2 left the voice channel (2nd) - Quaver (server2) will leave after Quaver on server1 leaves.

**After (Current order)**:
- user2 left the voice channel (1st) - Quaver (server2) will leave first 
- user1 left the stage channel (2nd) - Quaver (server1) will leave after Quaver on server2 leaves.

> user1 became last because he came back to the stage channel, then left right after (on step 5)

7. Quaver from server2 left the voice channel from inactivity.
8. Quaver from server1 left the stage channel from inactivity.
9. Quaver crashes.
10. See error
```
unhandledRejection
Unknown Voice State
DiscordAPIError: Unknown Voice State
    at RequestHandler.execute (/home/runner/GullibleQuestionableActivemovie/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/runner/GullibleQuestionableActivemovie/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async VoiceState.setSuppressed (/home/runner/GullibleQuestionableActivemovie/node_modules/discord.js/src/structures/VoiceState.js:254:5)
```

**Expected behavior**
Quaver should be operating normally on these kind of situations.

**Comment by zapteryx** [comment] 2022-01-02 03:07
thanks for the detailed repro steps, i'll follow up on this and see if i can get this fixed by next.9

**Comment by zapteryx** [comment] 2022-01-02 03:30
please test next.9 and see if the issue is still recurring. i removed redundancies and hopefully that is also the cause of the issue, if not i'm honestly not sure what to do LOL

**Closed** 2022-01-02 18:11 UTC
Labels: bug, released on @next
